name: rpi image builder

on:
  push:
    tags:
      - 'v*'

jobs:
  make-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DISTRO: ["debian", "raspios"]
        SUITE: ["buster", "bullseye"]
        ARCH: ["arm64", "armhf"]
        VARIANT: ["slim", "lite"]
    name: rpi-builder
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build images
        run: |
              echo "OS=${{ matrix.DISTRO }}" > config.txt
              echo "ARCHITECTURE=${{ matrix.ARCH }}" >> config.txt
              echo "COMPRESS=xz" >> config.txt
              echo "SUITE=${{ matrix.SUITE }}" >> config.txt
              echo "VARIANT=${{ matrix.VARIANT }}" >> config.txt
              sudo ./rpi-img-builder.sh
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: |
            ${{ matrix.DISTRO }}-${{ matrix.SUITE }}-${{ matrix.VARIANT }}-${{ matrix.ARCH }}.img.xz
