name: rpi image builder

on: [push, pull_request]

jobs:
  make-image:
    runs-on: ubuntu-latest
    name: rpi-builder
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo ./rpi-img-builder.sh
