name: rpi image builder

on: [push, pull_request]

jobs:
  make-image:
    runs-on: ubuntu-latest
    name: rpi-builder
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: |
          sudo ./rpi-img-builder.sh
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: v${{ steps.vars.outputs.tag }}
          draft: false
          files: |
            raspios-buster-lite-arm64.img.xz
