name: rpi image builder

on: push
  tags:
    - "v*.*.*"
  paths-ignore:
    - '**.md'

jobs:
  make-image:
    runs-on: ubuntu-latest
    name: rpi-builder
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build images
        run: |
          for distro in debian raspios; do
            for arch in arm64 armhf; do
              echo "OS=$distro" > config.txt
              echo "ARCHITECTURE=$arch" >> config.txt
              echo "COMPRESS=xz" >> config.txt
              echo "VARIANT=slim" >> config.txt
              sudo ./rpi-img-builder.sh
            done
          done
#      - name: Get Tag
#        id: vars
#        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: |
            debian-buster-slim-arm64.img.xz
            debian-buster-slim-armhf.img.xz
            raspios-buster-slim-arm64.img.xz
            raspios-buster-slim-armhf.img.xz
