name: rpi image builder

on: [push, pull_request]

jobs:
  make-image:
    runs-on: ubuntu-latest
    name: rpi-builder
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo ./rpi-img-builder.sh
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}          
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.vars.outputs.tag }}
          draft: true
          files: |
            raspios-buster-lite-arm64.img.xz
