name: rpi image builder
on:
  workflow_run:
    workflows: ["Make release"]
    types:
      - completed

jobs:
  make-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DISTRO: ["debian", "raspios"]
        SUITE: ["buster"]
        ARCH: ["arm64", "armhf"]
        VARIANT: ["slim", "lite"]
    name: rpi-builder
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build images
        run: |
              echo "OS=${{ matrix.DISTRO }}" > config.txt
              echo "ARCHITECTURE=${{ matrix.ARCH }}" >> config.txt
              echo "COMPRESS=xz" >> config.txt
              echo "RELEASE=${{ matrix.SUITE }}" >> config.txt
              echo "VARIANT=${{ matrix.VARIANT }}" >> config.txt
              sudo ./rpi-img-builder.sh
      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUBTOKEN }}"
          automatic_release_tag: "v1.0.0"
          prerelease: false
          files: |
            ${{ matrix.DISTRO }}-${{ matrix.SUITE }}-${{ matrix.VARIANT }}-${{ matrix.ARCH }}.img.xz
