name: rpi image builder
#on:
#  workflow_run:
#    workflows: ["Make release"]
#    types:
#      - completed
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
jobs:
  job1:
    tags:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - uses: dev-drprasad/delete-tag-and-release@v0.2.0
          with:
            delete_release: true
            tag_name: v1.0.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          with:
            tag_name: v1.0.0
            release_name: Release v1.0.0
            body: |
              Changes in this Release
              - First Change
              - Second Change
            draft: false
            prerelease: false
  job2:
    make-image:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          DISTRO: ["debian", "raspios"]
          SUITE: ["buster"]
          ARCH: ["arm64", "armhf"]
          VARIANT: ["slim", "lite"]
      name: rpi-builder
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Build images
          run: |
                echo "OS=${{ matrix.DISTRO }}" > config.txt
                echo "ARCHITECTURE=${{ matrix.ARCH }}" >> config.txt
                echo "COMPRESS=xz" >> config.txt
                echo "RELEASE=${{ matrix.SUITE }}" >> config.txt
                echo "VARIANT=${{ matrix.VARIANT }}" >> config.txt
                sudo ./rpi-img-builder.sh
        - name: Publish Release
          uses: softprops/action-gh-release@v1
          with:
            name: ${{ steps.vars.outputs.tag }}
            draft: false
            files: |
              ${{ matrix.DISTRO }}-${{ matrix.SUITE }}-${{ matrix.VARIANT }}-${{ matrix.ARCH }}.img.xz
